# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [binary]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    image_templates:
      - "ghcr.io/dayflower/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/dayflower/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/dayflower/{{ .ProjectName }}:{{ .Major }}-amd64"
      - "ghcr.io/dayflower/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-amd64"
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    image_templates:
      - "ghcr.io/dayflower/{{ .ProjectName }}:latest-arm64"
      - "ghcr.io/dayflower/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "ghcr.io/dayflower/{{ .ProjectName }}:{{ .Major }}-arm64"
      - "ghcr.io/dayflower/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-arm64"

docker_manifests:
  - name_template: "ghcr.io/dayflower/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/dayflower/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/dayflower/{{ .ProjectName }}:latest-arm64"
  - name_template: "ghcr.io/dayflower/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/dayflower/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/dayflower/{{ .ProjectName }}:{{ .Version }}-arm64"
  - name_template: "ghcr.io/dayflower/{{ .ProjectName }}:{{ .Major }}"
    image_templates:
      - "ghcr.io/dayflower/{{ .ProjectName }}:{{ .Major }}-amd64"
      - "ghcr.io/dayflower/{{ .ProjectName }}:{{ .Major }}-arm64"
  - name_template: "ghcr.io/dayflower/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/dayflower/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/dayflower/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-arm64"

changelog:
  disable: true

release:
  replace_existing_artifacts: true
