apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "backup-vaultwarden.fullname" . }}
  labels:
    {{- include "backup-vaultwarden.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule }}

  jobTemplate:
    metadata:
      {{- with .Values.pod.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backup-vaultwarden.labels" . | nindent 8 }}
        {{- with .Values.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

    spec:
      {{- if ne .Values.job.backoffLimit nil }}
      backoffLimit: {{ .Values.job.backoffLimit }}
      {{- end }}
      template:
        spec:
          {{- if .Values.rclone.destination }}
          initContainers:
            - name: setup-rclone-config
              image: busybox:latest
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -eux;
                  if [ ! -e {{ include "backup-vaultwarden.rCloneConfFullFileName" . | quote }} ]; then
                    echo "No rclone config found, copying from source";
                    cp {{ include "backup-vaultwarden.rCloneSourceConfFullFileName" . | quote }} {{ include "backup-vaultwarden.rCloneConfFullFileName" . | quote }};
                  else
                    echo "rclone config already exists, skipping copy";
                  fi;
              volumeMounts:
                - name: {{ .Values.rclone.liveConf.volume.name | required "rclone.liveConf.volume.name is required" | quote }}
                  mountPath: {{ include "backup-vaultwarden.rCloneConfMountPath" . | quote }}
                - name: rclone-conf-source
                  mountPath: {{ include "backup-vaultwarden.rCloneSourceConfMountPath" . | quote }}
                  readOnly: true
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                {{- if .Values.backup.fileName }}
                - "-o"
                - {{ .Values.backup.fileName | quote }}
                {{- end }}
                {{- if .Values.backup.target }}
                - "-t"
                - {{ .Values.backup.target | quote }}
                {{- end }}
                {{- if .Values.backup.logLevel }}
                - "-l"
                - {{ .Values.backup.logLevel | quote }}
                {{- end }}
                {{- if .Values.rclone.destination }}
                - "-r"
                - {{ .Values.rclone.destination | quote }}
                - "-c"
                - {{ include "backup-vaultwarden.rCloneConfFullFileName" . | quote }}
                {{- end }}
                {{- if .Values.rclone.preserveArchive }}
                - "-k"
                {{- end }}
                {{- with .Values.backup.encrypt }}
                {{- if .secretName }}
                - "-e"
                {{- end }}
                {{- end }}
                - {{ .Values.data.mountPath | default "/data" | quote }}
              {{- with .Values.backup.encrypt }}
              {{- if .secretName }}
              env:
                - name: BACKUP_PASSPHRASE
                  valueFrom:
                    secretKeyRef:
                      name: {{ .secretName | quote }}
                      key: {{ .key | default "BACKUP_PASSPHRASE" | quote }}
              {{- end }}
              {{- end }}
              volumeMounts:
                - name: {{ .Values.data.volume.name | required "data.volume.name is required" | quote }}
                  mountPath: {{ .Values.data.mountPath | default "/data" | quote }}
                {{- if .Values.rclone.destination }}
                - name: {{ .Values.rclone.liveConf.volume.name | required "rclone.liveConf.volume.name is required" | quote }}
                  mountPath: {{ include "backup-vaultwarden.rCloneConfMountPath" . | quote }}
                {{- end }}
                {{- with .Values.volumeMounts }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
              resources:
                {{- with .Values.pod }}
                {{- toYaml .resources | nindent 16 }}
                {{- end }}

          volumes:
            - {{- toYaml .Values.data.volume | nindent 14 }}
            {{- if .Values.rclone.destination }}
            - {{- toYaml .Values.rclone.liveConf.volume | nindent 14 }}
            - name: rclone-conf-source
              secret:
                secretName: {{ .Values.rclone.conf.secretName | required "rclone.conf.secretName is required when rclone.destination is defined" | quote }}
                items:
                  - key: {{ .Values.rclone.conf.secretKey | default "rclone.conf" | quote }}
                    path: {{ include "backup-vaultwarden.rCloneConfFileName" . | quote }}
            {{- end }}
            {{- with .Values.volumes }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

          restartPolicy: {{ .Values.job.restartPolicy | default "Never" }}

          {{- with .Values.pod }}
          {{- with .securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
